EXCLUDED_WORDS = ['για', 'με', 'cream', 'gel', 'tabs', 'κρέμα', 'spray', 'care', 'body', 'τμχ', 'la', 'sun', 'shampoo', 'oil', 'και', 'health', 'τεμάχια', 'face', 
'caps', 'προσώπου', 'plus', 'power', '50ml', 'aid', 'baby', 'μάσκα', 'hair', 'extra', 'lotion', 'spf50+', 'eye', 'color', 'spf50', 'kids', 'eau', 'de', 'vitamin',
'σαμπουάν', 'sensitive', 'serum', 'lip', 'skin', 'σε',
'200ml', 'hand', 'balm', 'της', 'mask', 'promo', 'καθαρισμού', 'cleanser', 'shower', 'garden', 'drops', 'αφρόλουτρο',
'beauty', 'δώρο', 'spf30', 'κατά', 'σώματος', 'set', 'elixir', 'intima', 'ultra', 'bee', 'my', 'γαλάκτωμα', 'natural', 'μέλι', 'πρόπολη', 'verset',
'youth', 'cleansing', 'aloe+colors', 'μαλλιών', 'την', 'water', 'επιθέματα', 'black', 'after', 'το', 'cerave', 'wash', 'άρωμα', 'the', 'test', 'soft', 'liquid', 'οδοντόκρεμα', 
'for', 'toothpaste', 'argan', 'τεστ', 'nail', 'dry', 'προφυλακτικά', 'των', 'mist', 'χρώμα', 'milk', 'velvet', 'blue', 'fresh', 'έλαιο', 'ενυδατική', 'του', 'moisturizing', 
'classic', 'aloe', 'pure', 'deo', 'with', 'fluid', 'διάλυμα', 'σιλικόνης', 'lavish', 'd3', 'creme', 'scrub', 'ταμπλέτες', 'night', 'med',
 'χωρίς', 'ξανθό', 'ματιών', 'men', 'medium', '1τμχ', 'of', 'foam', 'bath', 'ενυδατική', 'του', 'moisturizing', 'classic', 'aloe', 'pure', 'deo', 'with', 'fluid', 'διάλυμα', 
 'σιλικόνης', 'lavish', 'd3', 'creme', 'scrub', 'ταμπλέτες', 'night', 'med', 'χωρίς', 'klorane', 
 'sunscreen', 'and', 'daily', 'συμπλήρωμα', 'douche', 'express', 'τεμάχιο', 'red', 'toilette', 'effect', 'advanced', 'κάψουλες', 'original', 'spf', 'αντηλιακό', 'platinum', 
 'light', 'τον', 'lab.', 
 'wet', 'protect', 'pack', 'safe', 'premium', 'νυχιών', 'rose', 'προστασίας', 'matte', 'από', 'colorant', 'γυναικείο', 'hydrating', 'no', 'kit', 'lipstick', 'line', 
  'size', 'nasal', 'mesauda', 'πρόσωπο', 'vit', 'εγκυμοσύνης', 'active', 'white', 'intim', 'protection', 'wild', 'ffp2', 'roll-on', 'καραμέλες', 'χεριών', 'effaclar', 
  'σταγόνες', 'διατροφής', 'screen', 'crilen', 'μαλλιά', 'τεμ', 'intense', '1+1', 'mini', 'honey', 'lab', 'intimate', 'δισκία', 'tea', 'αιθέριο', 'vaginal', 'ορός', 
  'normal', 'ενυδατικό', 'one', 'γεύση', 'on', 'mild', 'hydra', 'junior', 'formula', 'scholl', 'butter', 'bausch', 'lomb', 'soleil', 'υαλουρονικό', 'you', 'day', 
  'αντηλιακή', 'σιρόπι', 'organic', 'large', 'fito+', 'tepe', 'to', 'bio', 'essential', 'βερνίκι', 'propolis', 'all', 'parfum', 'πιπίλα', 'colour', 'ανοιχτό', 
  'sachets', '50+', 'long', 'strips', 'real', 'powder', 'τζελ', 'free', 'βαφή', 'nature', 'ενυδάτωση', 'deodorant', 'repair', 'control', 'pink', 'thermale', 
  'γυαλιά', 'calm', 'fix', 'roll', 'παιδιά', 'ac-norm', 'up', 'sweet', 'υγρό', 'mint', 'λοσιόν', 'ξηρό', 'forte', 'anti', 'γάλα', 'σπρέι', 'invisible', 'super', 
  'foot', 'εντομοαπωθητικό', 'aqua', 'anatomic', 'μπεζ', 'λάδι', 'σετ', 'ελαστική', 'μαύρο', 'eff', 'travel', "chilly's", 'αποσμητικό', 'homme', 'soothing',
    'οδοντόβουρτσα', 'pharma', 'touch', 'syrup', 'ενυδάτωσης', 'bach', 'hyaluronic', 'λιπαντικό', 'mam', 'σκούρο', 'cleanance', 'χαμομήλι', 'baume', 'stick', 'oral', 
    'patch', 'mineral', 'always', 'ψηφιακό', 'ζελεδάκια', 'lait', 'haan', 'παιδικό', 'δέρμα', 'μηνών', 'invisibobble', 'orange', 'tinted', 'rapid', 
    'micellar', 'toleriane', 'μπλε', 'spring', 'stevia', 'πορτοκάλι', 'vera', 'multi', 'relief', 'capital', 'lierac', 'καστανό', 'complete', 'tonic', 'νερό', 
    'ph', 'λαιμό', 'brush', 'φυσικό', 'τριαντάφυλλο', 'xl', 'life', 'επιδερμίδες', 'small', 'master', 'wipes', 'θερμόμετρο', 'αλόη', 'στοματικό', 'intensive', 
    'jungle', 'luxurious', 'gentle', 'conditioner', 'thank', 'farmer', 'zinc', 'hygienic', 'lifting', 'total', 'complex', 'οφθαλμικές', 'protective', 'clean', 
    'δωρο', 'massage', 'eff.', '30caps', 'cleaner', 'a-derma', 'ταινίες', 'cold', 'rich', 'σώμα', 'age', 'true', 'βιολογικό', 'be', 'pro', 'glow', 'πολύ', 
    'parfums', 'magnesium', 'gold', 'αφρός', 'κόκκινο', 'green', 'comfort', 'αναβράζοντα', 'ροζ', '1τεμ', 'χρήσης', 'σαπούνι', 'βήχα', 'biome', 'sport', 
    'mousse', 'ηλίου', 'first', 'οξύ', 'energy', 'slim', 'βιταμίνη', 'άγριο', 'gift', 'τα', 'gloss', 'play', 'soap', 'systane', 'repel', 'sinus', 'ημέρας',
      'whitening', 'dr.', 'πράσινο', 'υψηλής', 'acid', 'oily', 'απαλό', 'refill', 'mouthwash', 'pleasure', 'micro', 'strong', 'bite', 'max', 'φακελάκια', 
      'emulsion', 'uvmune', 'spot', 'κρεμα', 'unisept', 'tangle', '48h', 'colors', 'vanilla', 'θήκη', 'ανταλλακτικά', 'pastilles', 'τονωτικό', 'podia', 'force', 
      'συσκευή', 'τη', '10%', 'τριχόπτωσης', 'dr', 'foundation', 'μελί', 'box', 'ice', 'blossom', 'φουσκάλες', 'make', 'herb', 'ml)', 'high', 'lemon', 'rinse', 
      'bottle', 'clinea', 'jasmine', 'ανδρικό', '4.4', 'παιδική', 'λεμόνι', 'pcs', 'λάμψη', 'feel', 'πούδρα', 'gr', 'προστασία', 'your', 'brightening', 'patches',
        'nettoyant', 'self', 'solution', 'time', 'compact', 'teezer', 'lift', 'perfect', 'αντιρυτιδική', 'ενηλίκων', 'foaming', 'facial', 'cup', 'pic', 'shine', 
        'μιας', 'μαντηλάκια', 'ευκάλυπτος', '24h', 'μάσκες', 'αντισηπτικό', 'adult', 'τους', 'σερβιέτες', 'uriage', 'edition', 'optofresh', 'women', 'chamomile', 'morello', 
        'eco', 
        '2x8', 'λαιμού', 'covid-19', 'olive', 'cranberry', 'emollient', 'στο', 'bar', 'epsilon', 'επιγονατίδα', 'easy', 'agan', 'πιεσόμετρο', 'so', 'urea', 'b5', 'jelly', 
        'fragrance', 'cs', 'hydration', 'eyes', 'spa', 'di', 'love', 'shop', 'όλους', 'τύπους', 'σιλικόνη', 'shave', 'μεσοδόντια', 'echinacea', 'retinol', '10τμχ', 'area', 
        'σκουλαρίκια', 'diffuser', 'yoghurt', 'fluide', 'just', 'chewable', 'dark', 'περιποίησης', 'cherry', 'creamy', 'ointment', 'cotton', 'σκόνη', 'use', 'arnica', 'ear', 
        'pomegranate', 'gum', 'γάζες', '30tabs', 'series', 'coconut', 'λάμψης', 'coffee', 'filter', 'θηλή', 'remedy', 'φυτικό', 'ginger', 'almond', 'καθαριστικό', 'x1', 'maxi', 
        'μάτια', 'firming', 'sugar', 'rescue', 'ελιά', 'φυτική', 'reed', 'bronze', 'μαύρη', 'sirop', '2τμχ', 'μετά', 'ωτοασπίδες', 'φακελίσκοι', 'bio-kult', 'instant', 
        'ανακούφιση', 'προβιοτικά', 'tablets', 'απλή', 'hot', 'deep', 'mo', 'hot', 'deep', 'mo', 'volcanic', 'λευκή', 'restore', 'breathe', 'refreshing', 'smoothing', 'μπιμπερό',
          'extreme', 'polish', 'moisturising', 'bag', 'men\'s', 'volcanic', 'λευκή', 'restore', 'breathe', 'refreshing', 'smoothing', 'μπιμπευωπίας', 'nr', 'start', 'ρινιρό', 
          'extreme', 'polish', 'blister', 'επίθεμα', 'αυτοκόλλητα', 'γάντια', 'πάνες', 'x2', 'multivitamin', 'υπέρτονο', 'protein', 'ανίχνευση', 'well', 'χειλιών', 'detox', 
          'moist', 'hydro', 'new', 'βρεφικό', 'ζευγάρι', 'sleep', 'βουρτσάκια', 'πρεσβe', 'anti-transpirant', 'fig\'υωπίας', 'nr', 'start', 'ρινι \'cough', 'guard', 'kid', 'lice', 
          'επιστραγαλίδα', 'paste', 'ταινία', 'tan', 'sκό', 'royal', 'απολέπισης', 'blister', 'επίθεμα', 'αυτοκόλλητα', 'γάντια', 'mains', 'ideal', 'πάνες', 'x2', 'multivitamin', 
          'ευαίσθητης', 'clear', 'ε \'υπέρτονο', 'protein', 'cosmetic', 'autan', 'repellent', 'γιαούρτι', 'προσώπου,', 'radiant', 'μεσαία', 'pants', 'χρήση', 'shape', '5', 
          'μέγεθος', 
          'silky', 'γκρι', 'μέντα', 'strawberry', 'balance', 'λιπαρή', 'booster', 'golden', 'vitality', 'anti-transpirant', 'fig\'aps', 'blemish', 'επιδερμίδα', 'nourishing', 
          'ii', 
          'ovules', 'derma', 'home', 'λεβάντα', 'αντικουνουπικό', 'scents', 'cough', 'otrisalin', 'guard', 'kid', 'lice', 'επιστραγαλίδα', 'paste', 'ταινία', 'range', 'υφής', 
          'tan', 
          'καθαρισμό', 'des', 'θερμοφόρα', 'kiss', 'correct', 'make-up', 'wise', 'candle', 'pepper', 'salt', 'spf20', 'yeux', 'ντεμακιγιάζ', 'cicalfate', 'jumbo', 'sticks', 
          'λιπαρές', 
          'contou', 'ανίχνευσης', 'minerals', 'vr', 'ευαίσθητης', 'mascara', 'grape', 'hylo', 'νύχτας', '3d', 'μελατονίνη', 'teint', 'ματ', 'ηλεκτρική', 'σταφύλι', 'lovely', 
          'αντλία', 
          'επίδεσμος', 'repellent', 'γιαούρτι', 'προσώπου,', 'radiant', 'μεσαία','περιοχής', 'pencil', 'tears', 'φικό', 'ζευγάρι', 'sleep', 'βουρτσάκια', 'πρεσβυωπίας', 'nr', 
          'start', 
          'ρινικό', 'royal', 'απολέπισης', 'blister', 'επίθεμα', 'αυτοκόλλητα', 'γάντια', 'mains', 'ideal', 'πάνες', 'x2', 'multivitamin', 'υπέρτονο', 'protein', 'spf15', 
          'μέγεθος', 
          'silky', 'γκρι',
 'μέντα', 'strawberry', 'λιπαρή', 'booster', 'me', 'anti-transpirant', 'fig', 'cough', 'guard', 'kid', 'lice', 'επιστραγαλίδα', 'paste', 'ταινία', 'tan', 'softgels', 'spf20', 
 'yeux', 
 'ντεμακιγιάζ', 'cicalfate', 'jumbo', 'sticks', 'λιπαρές', 'contour', 'ευαίσθητης', 'επίδεσμος', 'repellent', 'γιαούρτι', 'προσώπου,', 'radiant', 'μεσαία', 'pants', 'χρήση', 
 'shape', 'μωβ', 'melatonin', 'pr', 'ds', 'ευαίσθητες', 'έντονο', 'λευκό', '2000iu', 'h2o', 'ευαίσθητο', 'scented', 'golden', 'vitality', '60caps', 'blemish', 'επιδερμίδα', 
 'nourishing', 'ii', 'λεβάντα', 'αντικουνουπικό', 'scents', 'corrective', 'περλέ', 'κουτί', 'ετών', 'ξηρά', 'ελαστικό', 'τσάι', 'range', 'υφής', 'aloe+', 'brown', 'καθαρισμό', 
 'des', 'θερμοφόρα', 'kiss', 'correct', 'make-up', 'wise', 'candle', 'pepper', 'salt', 'pads', 'purifying', 'special', '5%', 'γέλη', 'σύστημα', 'νάρθηκας', 'αρωματικό', 'johns', 
 'maximum', 'μόνιμη', 'eyeliner', 'ανίχνευσης', 'adults', 'mascara', 'grape', 'νύχτας', '3d', 'μελατονίνη', 'teint', 'ματ', 'ηλεκτρική', 'σταφύλι', 'lovely', 'αντλία', 'omega-3', 
 'sorbet', 'λιπαρά', 'hippophae', 'ποδιών', 'dual', 'tube', 'holistic', 'μαλακό', 'περιοχής', 'pencil', 'tears', 'ζώνη', 'bijoux', 'αναζωογόνηση']
