EXCLUDED_WORDS = ['για', 'με', 'cream', 'gel', 'tabs', 'κρέμα', 'spray', 'care', 'body', 'τμχ', 'la', 'sun', 'shampoo', 'oil', 'και', 'health', 'τεμάχια', 'face', 
'caps', 'προσώπου', 'plus', 'power', '50ml', 'aid', 'baby', 'μάσκα', 'hair', 'extra', 'lotion', 'spf50+', 'eye', 'color', 'spf50', 'kids', 'eau', 'de', 'vitamin',
'σαμπουάν', 'sensitive', 'serum', 'lip', 'skin', 'σε',
'200ml', 'hand', 'balm', 'της', 'mask', 'promo', 'καθαρισμού', 'cleanser', 'shower', 'garden', 'drops', 'αφρόλουτρο',
'beauty', 'δώρο', 'spf30', 'κατά', 'σώματος', 'set', 'elixir', 'intima', 'ultra', 'bee', 'my', 'γαλάκτωμα', 'natural', 'μέλι', 'πρόπολη', 'verset',
'youth', 'cleansing', 'aloe+colors', 'μαλλιών', 'την', 'water', 'επιθέματα', 'black', 'after', 'το', 'cerave', 'wash', 'άρωμα', 'the', 'test', 'soft', 'liquid', 'οδοντόκρεμα', 'for', 'toothpaste', 'argan', 'τεστ', 'nail', 'dry', 'προφυλακτικά', 'των', 'mist', 'χρώμα', 'milk', 'velvet', 'blue', 'fresh', 'έλαιο', 'ενυδατική', 'του', 'moisturizing', 'classic', 'aloe', 'pure', 'deo', 'with', 'fluid', 'διάλυμα', 'σιλικόνης', 'lavish', 'd3', 'creme', 'scrub', 'ταμπλέτες', 'night', 'med',
 'χωρίς', 'ξανθό', 'ματιών', 'men', 'medium', '1τμχ', 'of', 'foam', 'bath', 'ενυδατική', 'του', 'moisturizing', 'classic', 'aloe', 'pure', 'deo', 'with', 'fluid', 'διάλυμα', 'σιλικόνης', 'lavish', 'd3', 'creme', 'scrub', 'ταμπλέτες', 'night', 'med', 'χωρίς', 'klorane', 
 'sunscreen', 'and', 'daily', 'συμπλήρωμα', 'douche', 'express', 'τεμάχιο', 'red', 'toilette', 'effect', 'advanced', 'κάψουλες', 'original', 'spf', 'αντηλιακό', 'platinum', 'light', 'τον', 'lab.', 
 'wet', 'protect', 'pack', 'safe', 'premium', 'νυχιών', 'rose', 'προστασίας', 'matte', 'από', 'colorant', 'γυναικείο', 'hydrating', 'no', 'kit', 'lipstick', 'line', 
  'size', 'nasal', 'mesauda', 'πρόσωπο', 'vit', 'εγκυμοσύνης', 'active', 'white', 'intim', 'protection', 'wild', 'ffp2', 'roll-on', 'καραμέλες', 'χεριών', 'effaclar', 
  'σταγόνες', 'διατροφής', 'screen', 'crilen', 'μαλλιά', 'τεμ', 'intense', '1+1', 'mini', 'honey', 'lab', 'intimate', 'δισκία', 'tea', 'αιθέριο', 'vaginal', 'ορός', 
  'normal', 'ενυδατικό', 'one', 'γεύση', 'on', 'mild', 'hydra', 'junior', 'formula', 'scholl', 'butter', 'bausch', 'lomb', 'soleil', 'υαλουρονικό', 'you', 'day', 
  'αντηλιακή', 'σιρόπι', 'organic', 'large', 'fito+', 'tepe', 'to', 'bio', 'essential', 'βερνίκι', 'propolis', 'all', 'parfum', 'πιπίλα', 'colour', 'ανοιχτό', 
  'sachets', '50+', 'long', 'strips', 'real', 'powder', 'τζελ', 'free', 'βαφή', 'nature', 'ενυδάτωση', 'deodorant', 'repair', 'control', 'pink', 'thermale', 
  'γυαλιά', 'calm', 'fix', 'roll', 'παιδιά', 'ac-norm', 'up', 'sweet', 'υγρό', 'mint', 'λοσιόν', 'ξηρό', 'forte', 'anti', 'γάλα', 'σπρέι', 'invisible', 'super', 
  'foot', 'εντομοαπωθητικό', 'aqua', 'anatomic', 'μπεζ', 'λάδι', 'σετ', 'ελαστική', 'μαύρο', 'eff', 'travel', "chilly's", 'αποσμητικό', 'homme', 'soothing',
    'οδοντόβουρτσα', 'pharma', 'touch', 'syrup', 'ενυδάτωσης', 'bach', 'hyaluronic', 'λιπαντικό', 'mam', 'σκούρο', 'cleanance', 'χαμομήλι', 'baume', 'stick'
    , 'oral', 'patch', 'mineral', 'always', 'ψηφιακό', 'ζελεδάκια', 'lait', 'haan', 'παιδικό', 'δέρμα', 'μηνών', 'invisibobble', 'orange', 'tinted', 'rapid', 
    'micellar', 'toleriane', 'μπλε', 'spring', 'stevia', 'πορτοκάλι', 'vera', 'multi', 'relief', 'capital', 'lierac', 'καστανό', 'complete', 'tonic', 'νερό', 
    'ph', 'λαιμό', 'brush', 'φυσικό', 'τριαντάφυλλο', 'xl', 'life', 'επιδερμίδες', 'small', 'master', 'wipes', 'θερμόμετρο', 'αλόη', 'στοματικό', 'intensive', 
    'jungle', 'luxurious', 'gentle', 'conditioner', 'thank', 'farmer', 'zinc', 'hygienic', 'lifting', 'total', 'complex', 'οφθαλμικές', 'protective', 'clean', 
    'δωρο', 'massage', 'eff.', '30caps', 'cleaner', 'a-derma', 'ταινίες', 'cold', 'rich', 'σώμα', 'age', 'true', 'βιολογικό', 'be', 'pro', 'glow', 'πολύ', 
    'parfums', 'magnesium', 'gold', 'αφρός', 'κόκκινο', 'green', 'comfort', 'αναβράζοντα', 'ροζ', '1τεμ', 'χρήσης', 'σαπούνι', 'βήχα', 'biome', 'sport', 
    'mousse', 'ηλίου', 'first', 'οξύ', 'energy', 'slim', 'βιταμίνη', 'άγριο', 'gift', 'τα', 'gloss', 'play', 'soap', 'systane', 'repel', 'sinus', 'ημέρας',
      'whitening', 'dr.', 'πράσινο', 'υψηλής', 'acid', 'oily', 'απαλό', 'refill', 'mouthwash', 'pleasure', 'micro', 'strong', 'bite', 'max', 'φακελάκια', 
      'emulsion', 'uvmune', 'spot', 'κρεμα', 'unisept', 'tangle', '48h', 'colors', 'vanilla', 'θήκη', 'ανταλλακτικά', 'pastilles', 'τονωτικό', 'podia', 'force', 
      'συσκευή', 'τη', '10%', 'τριχόπτωσης', 'dr', 'foundation', 'μελί', 'box', 'ice', 'blossom', 'φουσκάλες', 'make', 'herb', 'ml)', 'high', 'lemon', 'rinse', 
      'bottle', 'clinea', 'jasmine', 'ανδρικό', '4.4', 'παιδική', 'λεμόνι', 'pcs', 'λάμψη', 'feel', 'πούδρα', 'gr', 'προστασία', 'your', 'brightening', 'patches',
        'nettoyant', 'self', 'solution', 'time', 'compact', 'teezer', 'lift', 'perfect', 'αντιρυτιδική', 'ενηλίκων', 'foaming', 'facial', 'cup', 'pic', 'shine', 
        'μιας', 'μαντηλάκια', 'ευκάλυπτος', '24h', 'μάσκες', 'αντισηπτικό', 'adult', 'τους', 'σερβιέτες', 'uriage', 'edition', 'optofresh', 'women', 'chamomile', 'morello', 'eco']
